### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by racke** [interchange/TableEditor#55]
Recent commits did introduce a menu problem - no tables are shown any more on the left hand side.
Going back to f69eb79c8870d5f4e80482463e29434b9712fb85 fixes the problem.

Output of menu method looks like:

```json
Menu: [
   {
      "active" : 1,
      "items" : [
         {
            "class" : "Category",
            "name" : "Category",
            "url" : "#Category/list"
         },
         {
            "class" : "Product",
            "name" : "Product",
            "url" : "#Product/list"
         }
      ],
      "sort" : 100,
      "title" : "Tables"
   }
] 
```

**Comment by gregapompe** [comment]
True, I changed menu JSON, so there can be multiple menu blocks. You probably have custom index.html in your plugin and it uses old structure and finds nothing.

**Comment by racke** [comment]
Indeed. This kind of incompatible changes is dangerous, so please make a clear statement in the commit messages next time and drop us an email so we are aware of it.

**Comment by gregapompe** [comment]
OK. I try to avoid this kind of changes, but sometimes they are inevitable. I'll make it more clear next time.

**Comment by racke** [comment]
The change itself is fine - we just need to be kept up-to-date.
