### ISSUE TITLE
Restrict access to tables with read permission

### ISSUE THREAD

**Issue by racke** [interchange/TableEditor#59]
Currently we show the following elements on /#/Product/list even if user has only read permission for Product class:

* New Product button
* Delete icon
* Edit icon

At least the new product button and delete icon should be hidden.

**Comment by gregapompe** [comment]
Added
dcfec42fe537625ebd624d56b7fbba9e4a4b658f

**Comment by racke** [comment]
There is a glitch:

```
t/schema-info/interchange6.t .. keys on reference is experimental at /home/racke/interchange/TableEdit/lib/TableEdit/Permissions.pm line 86.
```

**Comment by gregapompe** [comment]
Ok, will patch it up.

**Comment by gregapompe** [comment]
fixed

**Comment by racke** [comment]
Thanks!
