### ISSUE TITLE
Query bug using BulkActions

### ISSUE THREAD

**Issue by racke** [interchange/TableEditor#68]
This happens if you search for products matching a string. Obviously quoting went wrong.

```
request to GET /api/Product/list crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'LOWER(me.name)' in 'where clause' [for Statement "SELECT COUNT( * ) FROM `products` `me` WHERE ( `LOWER(me`.`name)` LIKE ? )" with ParamValues: 0='%rod%'] at /home/racke/camp12/applications/TableEditor/lib/TableEdit/Routes/API.pm line 495
```

**Comment by SysPete** [comment]
Commit 86629086 from my branch `sql_literal_lower` branch should sort this one. There is another problem LOWER() still lurking on the code.
@racke can you see if this sort things?

**Comment by SysPete** [comment]
This issue is closed by commits that I've merged - see previous comments for info.
