### ISSUE TITLE
Logout doesn't work anymore

### ISSUE THREAD

**Issue by racke** [interchange/TableEditor#74]
Logout stopped working for me on several instances of TableEditor. No message on JS console or application log. Any idea?

**Comment by racke** [comment]
Reverting 2c278bcc576e6a899bf3085c1385bcfac92aeea5 fixed that. What was the idea of this commit?

**Comment by gregapompe** [comment]
There was some kind of flow problem, like $rootScope.logout() not being set yet in some cases. 
Apparently that wasn't done properly :)
