### ISSUE TITLE
Refresh content area

### ISSUE THREAD

**Issue by racke** [interchange/TableEditor#76]
We noticed that TableEditor has a confusing behaviour with the "Tables" links on the left hand side.

1. We load a class list like #/Product/list
2. Now we go to page 2 or add a filter.
3. Using the #/Product/list link wouldn't reload the first page / unfiltered results.

**Comment by gregapompe** [comment]
Fixed e15dc3f24dbae7c836cfec9076ab715adf56298c

**Comment by racke** [comment]
Thanks a lot!
